### ISSUE TITLE
Stucked at The "Loading Channel Information"

### ISSUE THREAD

**Issue by dashingsuma** [TwilioDevEd/twiliochat-android#10]
I created an account on twilio also created my own server which fetches me the token,  I made required changes according to the latest sdk in this app but i am stuck in the populateChannel method on mainchatActivity.

**Comment by berkus** [comment]
Please, attach logs. They give at least some insight to what is going on and will help us help you.

Since your logs may contain PII, such as your tokens, user login identities, account IDs etc, best way is to submit a support ticket with logs through [Support System](https://support.twilio.com).

[See the log collection manual here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md).

**Comment by dashingsuma** [comment]
Thanks for replying i just removed the progress bar from the code and further process are working...  I needed to ask wheater there is any app like this which runs on the twilio 3.0.0  as this works on 0.11.3 or it will be fine to use this old sdk...

**Comment by berkus** [comment]
0.11.3 is not supported, and will be hard End-of-Lifed around autumn this year, so if you plan to use it in production - just don't.

The demo app should work on 3.0.1 just fine, so if something doesn't - please collect logs as I suggested above and send them through Twilio support system. You can mention created ticket number here so it's easier to find.

**Comment by berkus** [comment]
Any updates on this?
