### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by GauravCreed** [TwilioDevEd/twiliochat-android#4]
Hi

I have already create Auth token from our server with own api so no need to generate auth token from ngrok then where i should place generated auth token and one more thing what should i pass in username field...?

when i pass dummy username then it will displaying sign in dialog continuously , not getting channel list, so how can i  get channel list from twillio account or any general channel list

Help me.
Thanks.

**Comment by mcelicalderon** [comment]
Hey @GauravCreed !

I'm not sure if I understand your problem correctly, but it seems like you are trying to change the code to input a fixed access token. Please note that this token is not the same as the Auth Token from your account. You can learn more about access tokens [here](https://www.twilio.com/docs/api/ip-messaging/guides/identity).

If you managed to get an access token that uses your account credentials you could change [this method](https://github.com/TwilioDevEd/twiliochat-android/blob/master/app/src/main/java/com/twilio/twiliochat/ipmessaging/IPMessagingClientManager.java#L143) to return a fixed string instead of fetching the token from the server application. It could look something like this:

``` java
private void fetchAccessToken(final FetchTokenListener listener) {
  listener.fetchTokenSuccess("your_fixed_access_token");    
}
```

If you need more information on access tokens please refer to step three of this repository's readme file or [this link](https://www.twilio.com/docs/api/ip-messaging/guides/identity#create-token). Also remember that generated tokens have an expiration period, that if is not specified is one hour. This android application will call the `fetchAccessToken` method automatically when the token is about to expire.

Let me know if you need further assistance :smiley:

**Comment by GauravCreed** [comment]
Hi TwilioDevEd

Thanks for the response,
As your instruction i follow the step and now i able to join channel and done communication.Thanks

A little more favor from you,for the problem, I have create a new activity in that just a button and on that button click i open LaunchActivity from the code, then when channel is populate that time we see the dialog Loading Channel Information, right?   After closing that dialog i press back Button and previous back to my created activity,And now problem is that i am not able to click my Button and not open LaunchActivity ,is it my User Interface is block ?, is this any solution...

this is my  [application](https://www.dropbox.com/s/a3rhabkkfg7t00i/app-debug.apk?dl=0)
Thanks

**Comment by mcelicalderon** [comment]
Hey @GauravCreed 

It looks like you are having issues with the actual application. If I understand correctly, you changed the main activity to have a button that will programatically launch `LaunchActivity`. If you want to be able to go back to an activity by pressing the back button you should avoid calling the `finish()` method after tapping the button. Refer to this article for more information http://developer.android.com/training/implementing-navigation/temporal.html

If you are working with [Twilio IP Messaging](https://www.twilio.com/ip-messaging) you might want to check out [these tutorials](https://github.com/TwilioDevEd?utf8=%E2%9C%93&query=twiliochat) were you can chat from a web browser or iOS. If you use the same credentials for token generation, you should be able to chat between mobile and web applications.

I'm closing this issue as you are no longer facing problems with the Twilio SDK. But, if you have further questions about our example applications don't hesitate to contact us.

**Comment by GauravCreed** [comment]
hi @mcelicalderon

i am disappointing to closing this issue, because i have still some little bit issue on regarding twilio channel,like i am getting some of these channel channel list fast 
`General Channel
 gaurav,
 general,
 general,
 sample,
 temp,
 Test Channel,
 Will .`

but some channel we can get after some time channel like `Jessica J., madison marchetti, SMU, My Team,etc.` i don't know why this is happening.any solution for this.

Thanks
